import random
#@python.coder_
import pyautogui as pg
import time
animal=("monkey","donkey","dog")
time.sleep(8)
for i in range(500):
    a=random.choice(animal)
    pg.write("you are a"+a)
    pg.press("enteryou are amonkey"
             "you are adog"
             "you are adog"
             "you are adonkey"
             "you are amonkey"
             "you are adog"
             "you are adog"
             "you are adonkey"
             "you are amonkey"
             "you are adonkey"
             "you are amonkey"
             "you are adog"
             "you are adonkey"
             "you are amonkey"
             "you are adonkey"
             "you are amonkey"
             "you are amonkey"
             "you are adonkey"
             "you are adog"
             "you are amonkey"
             "you are adog"
             "you are adog"
             "you are amonkey"
             "you are adog"
             "you are adog"
             "you are adog"
             "you are adog"
             "you are adonkey"
             "you are amonkey"
             "you are amonkey"
             "you are adonkey"
             "you are adog"
             "you are amonkey"
             "you are adog"
             "you are adonkey"
             "you are adonkey"
             "you are amonkey"
             "you are amonkey"
             "you are adog"
             "you are adonkey"
             "you are adog"
             "you are adog"
             "you are amonkey"
             "you are adog"
             "you are adog"
             "you are adog"
             "you are adog"
             "you are adonkey"
             "you are adonkey"
             "you are adog"
             "you are adonkey"
             "you are amonkey"
             "you are amonkey"
             "you are adog"
             "you are adonkey"
             "you are amonkey"
             "you are adog"
             "you are amonkey"
             "you are amonkey"
             "you are adog"
             "you are adonkey"
             "you are adog"
             "you are amonkey"
             "you are amonkey"
             "you are amonkey"
             "you are adonkey"
             "you are adog"
             "you are adonkey"
             "you are amonkey"
             "you are adonkey"
             "you are adog"
             "you are amonkey"
             "you are adog"
             "you are adonkey"
             "you are adonkey"
             "you are adonkey"
             "you are amonkey"
             "you are adonkey"
             "you are adonkey"
             "you are amonkey"
             "you are adonkey"
             "you are adonkey"
             "you are amonkey"
             "you are amonkey"
             "you are adonkeyyou are adogare adogyou are adonkeyyou are adogyou are amonkeyyou are adonkeyyou are adonkeyyou are adogyou are adogyou are adonkeyyou are amonkeyyou are adonkeyyou are adonkeyyou are adogyou are adonkeyyou are adonkeyyou are adonkeyyou are amonkeyyou are amonkeyyou are adogyou are adonkeyyou are adonkeyyou are adonkeyyou are amonkeyyou are adogyou are amonkeyyou are adogyou are adonkeyyou are adogyou are adonkeyyou are adonkeyyou are adogyou are adonkeyyou are adogyou are adonkeyyou are adonkeyyou are adogyou are adonkeyyou are adonkeyyou are adogyou are adogyou are adonkeyyou are adonkeyyou are adogyou are amonkeyyou are adonkey")
